credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "GitHub pass"
          id: "GitHub_ID"
          password: "{AQAAABAAAAAwKqIlA3wUbNqxkz4m27QWTr2YCKejc55Siu3el1ZBhT5FduAwhFb/m1hV57aN0fix3Um47hok1VdN/hMWA13MGA==}"
          scope: GLOBAL
          username: "modifikator18"
    - credentials:
      - string:
          id: "botSecret"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwdZ4JtXZL9dpdH2kH1wglxRiiKzVeR7NNKnRA5LylR1R+XgNOm1PxD0lEA2GGtp+g7EKcv60JlQufCVyAaqLvPw==}"
      - string:
          id: "chatId"
          scope: GLOBAL
          secret: "{AQAAABAAAAAQ7Vn07bdI0V9/fWj2aTE4Zydt6rRmE5rsUppiktPBhRk=}"
      domain:
        name: "Telegram"

jenkins:
  systemMessage: "<div style='border-radius:10px; text-align: center; padding:20px; font-size:160%; background-color: tomato;'>Jenkins configured automatically by Jenkins Configuration as Code plugin</div><br>"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  numExecutors: 3
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        name: "admin"
        password: ${JENKINS_ADMIN_PASSWORD}

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  scriptApproval:
    approvedSignatures:
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"

unclassified:
  location:
    url: ${JENKINS_URL}
  locale:
    ignoreAcceptLanguage: true
    systemLocale: "en"

jobs:
  - file: /var/jenkins_home/casc_configs/CI.groovy
#  - file: /var/jenkins_home/casc_configs/CD.groovy
  - file: /var/jenkins_home/casc_configs/1.groovy
#/var/jenkins_home/casc_configs/